module.exports = {  
   "amex":{  
      "name":"American Express",
      "logo":"https://upload.wikimedia.org/wikipedia/commons/3/30/American_Express_logo.svg",
      "format":"#### #### #### ###", // you can define format here, or in rules section 
      "rules":[  
         {  
            "lengths":[  
               15
            ],
            "start":[  
               34,
               37
            ],
            "checksum":"luhn"
         } //, { "lengths": [...], "start": [...], "checksum": [...] }
      ]
   },
   "bc":{  
      "name":"Bankcard",
      "logo":"https://en.wikipedia.org/wiki/Bankcard#/media/File:Bankcard_standard_logo.png",
      "rules":[  
         {  
            "lengths":[  
               16
            ],
            "start":[  
               5610,
               560221,
               560222,
               560223,
               560224,
               560225
            ],
            "checksum":"luhn"
         }
      ]
   },
   "cup":{  
      "name":"China UnionPay",
      "logo":"https://upload.wikimedia.org/wikipedia/commons/1/1b/UnionPay_logo.svg",
      "rules":[  
         {  
            "lengths":[  
               16,
               17,
               18,
               19
            ],
            "start":[  
               62
            ],
            "checksum":"luhn"
         }
      ]
   },
   "dine":{  
      "name":"Diners Club enRoute",
      "logo":"https://upload.wikimedia.org/wikipedia/commons/a/a6/Diners_Club_Logo3.svg",
      "rules":[  
         {  
            "lengths":[  
               15
            ],
            "start":[  
               2014,
               2149
            ],
            "checksum":false
         }
      ]
   },
   "dini":{  
      "name":"Diners Club International",
      "logo":"https://upload.wikimedia.org/wikipedia/commons/a/a6/Diners_Club_Logo3.svg",
      "rules":[  
         {  
            "lengths":[  
               14,
               15,
               16,
               17,
               18,
               19
            ],
            "start":[  
               36
            ],
            "checksum":"luhn"
         },
         {  
            "lengths":[  
               16,
               17,
               18,
               19
            ],
            "start":[  
               300,
               301,
               302,
               303,
               304,
               305,
               3095,
               38,
               39
            ],
            "checksum":"luhn"
         }
      ]
   },
   "dinus":{  
      "name":"Diners Club", // US & Canada, co-branded MasterCards 
      "logo":"https://upload.wikimedia.org/wikipedia/commons/a/a6/Diners_Club_Logo3.svg",
      "rules":[  
         {  
            "lengths":[  
               16
            ],
            "start":[  
               54,
               55
            ],
            "checksum":"luhn"
         }
      ]
   },
   "disc":{  
      "name":"Discover",
      "logo":"https://upload.wikimedia.org/wikipedia/commons/5/57/Discover_Card_logo.svg",
      "rules":[  
         {  
            "lengths":[  
               16,
               17,
               18,
               19
            ],
            "start":[  
               6011,
               64,
               54
            ],
            "checksum":"luhn"
         }
      ]
   },
   "rupay":{  
      "name":"RuPay",
      "logo":"https://upload.wikimedia.org/wikipedia/commons/d/d1/RuPay.svg",
      "rules":[  
         {  
            "lengths":[  
               16
            ],
            "start":[  
               60,
               6521
            ],
            "checksum":"luhn"
         }
      ]
   },
   "inter":{  
      "name":"Interpayment",
      "logo":"",
      "rules":[  
         {  
            "lengths":[  
               16,
               17,
               18,
               19
            ],
            "start":[  
               636
            ],
            "checksum":"luhn"
         }
      ]
   },
   "insta":{  
      "name":"Instapayment",
      "logo":"",
      "rules":[  
         {  
            "lengths":[  
               16
            ],
            "start":[  
               637,
               638,
               639
            ],
            "checksum":"luhn"
         }
      ]
   },
   "jcb":{  
      "name":"JCB",
      "logo":"https://upload.wikimedia.org/wikipedia/commons/4/40/JCB_logo.svg",
      "rules":[  
         {  
            "lengths":[  
               16,
               17,
               18,
               19
            ],
            "start": (function(){
			var a = [], i;
			for (i=3529;i<=3589;i++) {  
				a.push(i);
			}
			return a;
		     }()),
            "checksum":"luhn"
         }
      ]
   },
   "maest":{  
      "name":"Maestro",
      "logo":"https://upload.wikimedia.org/wikipedia/commons/8/80/Maestro_2016.svg",
      "rules":[  
         {  
            "lengths":[  
               12,
               13,
               14,
               15,
               16,
               17,
               18,
               19
            ],
            "start":[  
               50,
               56,
               57,
               58,
               639,
               67
            ],
            "checksum":"luhn"
         }
      ]
   },
   "dank":{  
      "name":"Dankort",
      "logo":"https://upload.wikimedia.org/wikipedia/commons/5/51/Dankort_logo.png",
      "rules":[  
         {  
            "lengths":[  
               16
            ],
            "start":[  
               5019,
               4571
            ],
            "checksum":"luhn"
         }
      ]
   },
   "mir":{  
      "name":"MIR",
      "logo":"https://upload.wikimedia.org/wikipedia/commons/a/a9/Nspk-mir.png",
      "rules":[  
         {  
            "lengths":[  
               16
            ],
            "start":[  
               2200,
               2201,
               2202,
               2203,
               2204
            ],
            "checksum":"luhn"
         }
      ]
   },
   "mc":{  
      "name":"MasterCard",
      "logo":"https://upload.wikimedia.org/wikipedia/commons/2/2a/Mastercard-logo.svg",
      "rules":[  
         {  
            "lengths":[  
               16
            ],
            "start":[  
               51,
               52,
               53,
               54,
               55
            ],
            "checksum":"luhn"
         },
         {  
            "lengths":[  
               16
            ],
            "start":[  
               222,
               223,
               224,
               225,
               226,
               227,
               228,
               229,
               23,
               24,
               25,
               26,
               270,
               271,
               2720
            ],
            "checksum":"luhn"
         }
      ]
   },
   "troy":{  
      "name":"Troy",
      "logo":"",
      "rules":[  
         {  
            "lengths":[  
               16
            ],
            "start":[  
               97920,
               97921,
               97922,
               97923,
               97924,
               97925,
               97926,
               97927,
               97928
            ],
            "checksum":"luhn"
         }
      ]
   },
   "visa":{  
      "name":"Visa",
      "logo":"https://upload.wikimedia.org/wikipedia/commons/5/53/Visa_2014_logo_detail.svg",
      "format":"#### #### #### ####",
      "rules":[  
         {  
            "lengths":[  
               16
            ],
            "start":[  
               4
            ],
            "checksum":"luhn"
         }
      ]
   },
   "utap":{  
      "name":"UTAP",
      "logo":"",
      "rules":[  
         {  
            "lengths":[  
               15
            ],
            "start":[  
               1
            ],
            "checksum":"luhn"
         }
      ]
   },
   "verve":{  
      "name":"Verve",
      "logo":"",
      "rules":[  
         {  
            "lenghts":[  
               16,
               19
            ],
            "start":[  
               5060,
               5061,
               65000,
               65002,
               650003,
               650004,
               650005,
               650006,
               650007,
               650008,
               650009,
               65001,
               650020,
               650021,
               650022,
               650023,
               650024,
               650025,
               650026,
               650027
            ],
            "checksum":"luhn"
         }
      ]
   }
}